#spring.application.name=jvoq-microservicio-monederos
#server.port=8003
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#eureka.instance.instance-id=${spring.application.name}:${random.value}
#spring.data.mongodb.uri=mongodb+srv://jvoq:admin@cluster0.8uq6g.mongodb.net/db-microservicio-operaciones?retryWrites=true&w=majority
#spring.config.import=optional:configserver:http://config-server:8888
#spring.config.import=optional:configserver:http://localhost:8888
#spring.profiles.active=dev





#config kafka
server:
  port: 8700
spring:
  application:
    name: jvoq-microservicio-monederos
  kafka:
    bootstrap-servers: moped-01.srvs.cloudkafka.com:9094,moped-02.srvs.cloudkafka.com:9094,moped-03.srvs.cloudkafka.com:9094
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="o67d934g" password="Vn0UzJmbpHkapICUdmQhfvsIjGhCHJzJ";
  cloud:
    function:
      definition: actualizarSaldo
    stream:
      bindings:
        transaccion-in-0:
          destination: o67d934g-transaccion
